// Importe les modules nécessaires ici

const usersData = [
  {
    nom: "Alice Smith",
    adresse: "123 Main Street",
    cp: "75001",
    ville: "Paris",
    telephone: "+33 1 23 45 67 89",
    email: "alice.smith@cci.com",
    motdepasse: "MotDePasse123",
  },
  {
    nom: "Bob Johnson",
    adresse: "456 Second Avenue",
    cp: "91000",
    ville: "Évry",
    telephone: "+33 9 87 65 43 21",
    email: "bob.johnson@cci.com",
    motdepasse: "BobMotDePasse",
  },
  {
    nom: "Carol Davis",
    adresse: "789 Central Boulevard",
    cp: "69001",
    ville: "Lyon",
    telephone: "+33 6 54 32 10 98",
    email: "carol.davis@cci.com",
    motdepasse: "CarolPass123",
  },
  {
    nom: "David Wilson",
    adresse: "567 Oak Lane",
    cp: "34000",
    ville: "Montpellier",
    telephone: "+33 4 56 78 90 12",
    email: "david.wilson@cci.com",
    motdepasse: "DavidPass",
  },
  {
    nom: "Emily Taylor",
    adresse: "890 Pine Street",
    cp: "13001",
    ville: "Marseille",
    telephone: "+33 7 89 01 23 45",
    email: "emily.taylor@cci.com",
    motdepasse: "EmilyPass123",
  },
  {
    nom: "Frank Brown",
    adresse: "234 Birch Avenue",
    cp: "67000",
    ville: "Strasbourg",
    telephone: "+33 3 21 43 65 87",
    email: "frank.brown@cci.com",
    motdepasse: "FrankPass",
  },
  {
    nom: "Grace Miller",
    adresse: "678 Elm Road",
    cp: "69002",
    ville: "Lyon",
    telephone: "+33 6 78 90 12 34",
    email: "grace.miller@cci.com",
    motdepasse: "GracePass123",
  },
  {
    nom: "Henry Turner",
    adresse: "345 Cedar Street",
    cp: "33000",
    ville: "Bordeaux",
    telephone: "+33 5 43 65 87 09",
    email: "henry.turner@cci.com",
    motdepasse: "HenryPass",
  },
  {
    nom: "Isabel Garcia",
    adresse: "456 Maple Avenue",
    cp: "75002",
    ville: "Paris",
    telephone: "+33 1 34 56 78 90",
    email: "isabel.garcia@cci.com",
    motdepasse: "IsabelPass123",
  },
  {
    nom: "Jack White",
    adresse: "789 Walnut Lane",
    cp: "13002",
    ville: "Marseille",
    telephone: "+33 7 89 01 23 45",
    email: "jack.white@cci.com",
    motdepasse: "JackPass",
  },
];
